# Generated by Django 3.2 on 2021-06-10 14:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0012_alter_post_last_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='last_modified',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 10, 19, 43, 39, 690436)),
        ),
    ]
