# Generated by Django 3.2 on 2021-06-14 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0017_alter_post_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='publish',
        ),
    ]
