# Generated by Django 3.2 on 2021-06-16 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0018_remove_post_publish'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='created_on',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='created_on',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='updated_on',
            new_name='updated',
        ),
        migrations.AddField(
            model_name='comment',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
