# Generated by Django 3.2.4 on 2021-06-25 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0019_auto_20210616_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postimage',
            field=models.ImageField(blank=True, upload_to='media/postimages/'),
        ),
    ]
