# Generated by Django 3.2 on 2021-06-17 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20210616_2030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='lname',
        ),
        migrations.AlterField(
            model_name='contact',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='fname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(max_length=400),
        ),
    ]
